version: '3.8'
services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/user-service
      JWT_SECRET: 0pysgYI7oED91Nyx0xMsztAl
      PORT: 5000
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: